name: Triggered Workflow

env:
  RUNNERS_OPTIONS: -c cookies=enabled
  jarPath: "C:\\Program Files (x86)\\DBmaestro\\DOP Server\\Agent\\DBmaestroAgent.jar"
  DBMprojectName: "TMNA_PGSQL_BYTASK_PRJCT"
  DBMauthType: "DBmaestroAccount"
  DBMuserName: "poc@dbmaestro.com"
  DBMauthToken: "7KI5tL3ywYAZLB8FUY9fzJyekemgtG45"
  DBMserver: "DOPX-BERKE"
  DBMVersion: "V9"
  DBMRSSchema: "demors"
  PACKAGE: test




on:
  repository_dispatch:
    inputs:
      message:
        default: production
  workflow_dispatch:


jobs:
  build:
    runs-on: self-hosted




    steps:
      - name: Print Event
        run: echo "This is a triggered event. ${{ github.event.client_payload.input_value }}  ${{ github.event.client_payload.input_value2 }}"

      - name: Download files and process
        run: |
          cd C:\\workspace\\tmna_git\\download
          whoami
          dir
          git fetch
          git status
          git checkout ${{ matrix.branch_name }}

          echo "Current build number: ${{ github.run_number }}"
                    powershell |
            # Example PowerShell script
            $packageName = "${{ matrix.package_name }}"
            Write-Host "Running PowerShell script for package: $packageName"
            # Add your PowerShell commands here

            # Add your additional PowerShell commands here
          powershell |
            # Example PowerShell script for downloading and processing files
            $sourceDirectory = "C:\\workspace\\tmna_git\\download"
            $targetDirectory1 = "C:\\workspace\\tmna_git\\packages\\V_${{ github.run_number }}\\TANGO_CLIENT1_PROD_APPS\\Upgrade"
            $targetDirectory2 = "C:\\workspace\\tmna_git\\packages\\V_${{ github.run_number }}\\TANGO_CLIENT1_PROD_TMCS\\Upgrade"



      - name: Compress package
        run: |
          java -jar "${{ env.agent_full_path }}" -CreateManifestFile -PathToScriptsFolder "C:\\workspace\\tmna_git\\packages\\V_${{ github.run_number }}"

          # Zip everything under the specified folder
          Compress-Archive -Path "C:\\workspace\\tmna_git\\packages\\V_${{ github.run_number }}\\*" -DestinationPath "C:\\workspace\\tmna_git\\packages\\V_${{ github.run_number }}.zip" -Force



      - name: DBMaestro Task
        run: java -jar "${{ env.jarPath }}" -Upgrade -ProjectName ${{ env.DBMprojectName }} -EnvName "Release Source" -PackageName ${{ env.DBMVersion }} -Server DOPX-BERKE:8020 -AuthType ${{ env.DBMauthType }} -UserName ${{ env.DBMuserName }} -Password ${{ env.DBMauthToken }}
