name: Triggered Workflow

env:
  RUNNERS_OPTIONS: -c cookies=enabled
  jarPath: "C:\\Program Files (x86)\\DBmaestro\\DOP Server\\Agent\\DBmaestroAgent.jar"
  DBMprojectName: "TMNA_PGSQL_BYTASK_PRJCT"
  DBMauthType: "DBmaestroAccount"
  DBMuserName: "poc@dbmaestro.com"
  DBMauthToken: "7KI5tL3ywYAZLB8FUY9fzJyekemgtG45"
  DBMserver: "DOPX-BERKE"
  DBMVersion: "V9"
  DBMRSSchema: "demors"
  PACKAGE: test
  BRANCH_NAME: "20231127"




on:
  repository_dispatch:
    inputs:
      message:
        default: production
  workflow_dispatch:


jobs:
  build:
    runs-on: self-hosted




    steps:
      - name: Print Event
        run: echo "This is a triggered event. ${{ github.event.client_payload.input_value }}  ${{ github.event.client_payload.input_value2 }}"

      - name: Download files and process
        run: |
          cd C:\\workspace\\tmna_git\\download
          whoami
          dir
          git fetch
          git status
          git checkout ${{ env.BRANCH_NAME }}
          echo "Current build number: ${{ github.run_number }}"
      - name: Run PowerShell Script
        shell: pwsh
        run: |
          # Your PowerShell script goes here
          Write-Host "Hello from PowerShell script!"
          Get-ChildItem -Path .\ -Recurse | ForEach-Object {
              Write-Host "File: $($_.FullName)"
          }
      - name: Download Files
        run: |
          cd C:\\workspace\\tmna_git\\packages
          mkdir "V_${{ github.run_number }}"
          mkdir "V_${{ github.run_number }}\\TOYOTA_RS"
          mkdir "V_${{ github.run_number }}\\TOYOTA_RS\\Upgrade"
          mkdir "V_${{ github.run_number }}\\TOYOTA_RS\\Downgrade"
          
      - name: Run PowerShell Script
        shell: pwsh
        run: |
           $destinationDirectory = "C:\\workspace\\tmna_git\\packages\\V_${{github.run_number}}"
           $targetDirectory1 = "${destinationDirectory}\\TOYOTA_RS\\Upgrade"   
           Write-Host "File: $targetDirectory1  $destinationDirectory  "
           $sourceDirectory= "C:\\workspace\\tmna_git\\download"
           Get-ChildItem -File -Recurse $sourceDirectory | ForEach-Object {
                          $file = $_
                          $extension = $file.Extension.TrimStart('.')
                          Write-Host "File Name: $($file.Name)"
                          if ($extension -eq 'trg') {
                              if ($file.Directory.Name -eq 'APPS') {
                                  $newName = "01_" + $file.BaseName + ".sql"
                                  $newPath = Join-Path $targetDirectory1 $newName
                                  Copy-Item -Path $file.FullName -Destination $newPath -Force
                                  Write-Host "Moved and renamed: $($file.FullName) to $($newPath)"
                              } 
                          } else {
                              Write-Host "Skipped: $($file.FullName)"
                          }
                          }
                                        


        
          
      - name: Compress package
        run: |
          java -jar "${{ env.jarPath }}" -CreateManifestFile -PathToScriptsFolder "C:\\workspace\\tmna_git\\packages\\V_${{ github.run_number }}"
          # Zip everything under the specified folder
          Compress-Archive -Path "C:\\workspace\\tmna_git\\packages\\V_${{ github.run_number }}\\*" -DestinationPath "C:\\workspace\\tmna_git\\packages\\V_${{ github.run_number }}.zip" -Force
      - name: DBMaestro Task
        run: java -jar "${{ env.jarPath }}" -Upgrade -ProjectName ${{ env.DBMprojectName }} -EnvName "Release Source" -PackageName ${{ env.DBMVersion }} -Server DOPX-BERKE:8020 -AuthType ${{ env.DBMauthType }} -UserName ${{ env.DBMuserName }} -Password ${{ env.DBMauthToken }}
